import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const TELEGRAM_BOT_TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN") ?? "";
const TELEGRAM_CHAT_ID = Deno.env.get("TELEGRAM_CHAT_ID") ?? "";

interface PatternCount {
  name: string;
  description: string;
  count: number;
  source_ids: string[];
}

async function sendTelegram(message: string): Promise<void> {
  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) return;
  await fetch(
    `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: TELEGRAM_CHAT_ID,
        text: message,
        parse_mode: "Markdown",
      }),
    },
  );
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "POST required" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

  try {
    // Analyze n8n_ideas across all processed conversations for recurring patterns
    const { data: allProcessed, error } = await supabase
      .from("conv_processed")
      .select("id, n8n_ideas, skills")
      .in("status", ["routed", "partially_routed", "extracted"]);

    if (error) throw new Error(error.message);
    if (!allProcessed || allProcessed.length === 0) {
      return new Response(
        JSON.stringify({ message: "No processed conversations to analyze", patterns: [] }),
        { headers: { "Content-Type": "application/json" } },
      );
    }

    // Count n8n idea patterns by normalized name
    const ideaCounts = new Map<string, PatternCount>();
    for (const row of allProcessed) {
      for (const idea of (row.n8n_ideas ?? []) as Array<Record<string, string>>) {
        const key = (idea.name ?? idea.description ?? "").toLowerCase().trim();
        if (!key) continue;
        const existing = ideaCounts.get(key) ?? {
          name: idea.name ?? key,
          description: idea.description ?? "",
          count: 0,
          source_ids: [],
        };
        existing.count++;
        existing.source_ids.push(row.id);
        ideaCounts.set(key, existing);
      }
    }

    // Count skill patterns
    const skillCounts = new Map<string, PatternCount>();
    for (const row of allProcessed) {
      for (const skill of (row.skills ?? []) as Array<Record<string, string>>) {
        const key = (skill.name ?? skill.description ?? "").toLowerCase().trim();
        if (!key) continue;
        const existing = skillCounts.get(key) ?? {
          name: skill.name ?? key,
          description: skill.description ?? "",
          count: 0,
          source_ids: [],
        };
        existing.count++;
        existing.source_ids.push(row.id);
        skillCounts.set(key, existing);
      }
    }

    // Patterns appearing 3+ times are candidates for auto-generation
    const threshold = 3;
    const recurringIdeas = [...ideaCounts.values()].filter(
      (p) => p.count >= threshold,
    );
    const recurringSkills = [...skillCounts.values()].filter(
      (p) => p.count >= threshold,
    );

    const autoGenerated: Array<{ type: string; name: string; count: number }> = [];

    // Generate skill stubs for recurring patterns
    for (const pattern of recurringSkills) {
      // Check if already exists in routing log as auto-generated
      const { data: existingLog } = await supabase
        .from("conv_routing_log")
        .select("id")
        .eq("route_type", "auto_skill")
        .eq("destination", pattern.name)
        .maybeSingle();

      if (existingLog) continue;

      await supabase.from("conv_routing_log").insert({
        conv_processed_id: pattern.source_ids[0],
        route_type: "auto_skill",
        payload: {
          name: pattern.name,
          description: pattern.description,
          occurrence_count: pattern.count,
          source_conversations: pattern.source_ids,
        },
        destination: pattern.name,
        status: "auto_generated",
        routed_at: new Date().toISOString(),
      });

      autoGenerated.push({
        type: "skill",
        name: pattern.name,
        count: pattern.count,
      });
    }

    // Generate n8n workflow stubs for recurring ideas
    for (const pattern of recurringIdeas) {
      const { data: existingLog } = await supabase
        .from("conv_routing_log")
        .select("id")
        .eq("route_type", "auto_n8n_stub")
        .eq("destination", pattern.name)
        .maybeSingle();

      if (existingLog) continue;

      await supabase.from("conv_routing_log").insert({
        conv_processed_id: pattern.source_ids[0],
        route_type: "auto_n8n_stub",
        payload: {
          name: pattern.name,
          description: pattern.description,
          occurrence_count: pattern.count,
          source_conversations: pattern.source_ids,
        },
        destination: pattern.name,
        status: "auto_generated",
        routed_at: new Date().toISOString(),
      });

      autoGenerated.push({
        type: "n8n_workflow",
        name: pattern.name,
        count: pattern.count,
      });
    }

    // Telegram summary
    if (autoGenerated.length > 0) {
      const skills = autoGenerated.filter((a) => a.type === "skill");
      const workflows = autoGenerated.filter((a) => a.type === "n8n_workflow");
      await sendTelegram(
        `*CONV-PROC Self-Expansion*\n` +
          `Analyzed: ${allProcessed.length} conversations\n` +
          `Auto-generated skills: ${skills.length}\n` +
          `Auto-generated n8n stubs: ${workflows.length}\n` +
          `Threshold: ${threshold}+ occurrences`,
      );
    }

    return new Response(
      JSON.stringify({
        analyzed: allProcessed.length,
        recurring_ideas: recurringIdeas.length,
        recurring_skills: recurringSkills.length,
        auto_generated: autoGenerated,
        threshold,
      }),
      { headers: { "Content-Type": "application/json" } },
    );
  } catch (err) {
    return new Response(
      JSON.stringify({ error: (err as Error).message }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
});
