INSERT INTO config (key, value, last_verified, source_url, next_check, confidence) VALUES
('iof_brl', '0.0038', NOW(), 'https://www.gov.br/receitafederal/pt-br', NOW() + INTERVAL '30 days', 'confirmed'),
('tax_ngn', '0', NOW(), 'Nigeria Tax Act 2025', NOW() + INTERVAL '90 days', 'confirmed'),
('tax_inr', '0', NOW(), 'Reserve Bank of India', NOW() + INTERVAL '90 days', 'confirmed'),
('tax_mxn', '0', NOW(), 'SAT Mexico', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_wise_flat', '0.55', NOW(), 'https://wise.com/gb/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_wise_pct', '0.0065', NOW(), 'https://wise.com/gb/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_wise_spread', '0.003', NOW(), 'https://wise.com/gb/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_revolut_flat', '0', NOW(), 'https://revolut.com/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_revolut_pct', '0.005', NOW(), 'https://revolut.com/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_revolut_spread', '0.004', NOW(), 'https://revolut.com/pricing/', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_bank_flat', '25', NOW(), 'Average Irish bank wire fees', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_bank_pct', '0.018', NOW(), 'Average Irish bank wire fees', NOW() + INTERVAL '90 days', 'confirmed'),
('fee_bank_spread', '0.022', NOW(), 'Average Irish bank wire fees', NOW() + INTERVAL '90 days', 'confirmed'),
('nudge_limit_free', '3', NOW(), 'Product spec', NULL, 'confirmed'),
('nudge_limit_standard', '10', NOW(), 'Product spec', NULL, 'confirmed'),
('nudge_limit_pro', '30', NOW(), 'Product spec', NULL, 'confirmed'),
('watch_limit_free', '1', NOW(), 'Product spec', NULL, 'confirmed'),
('watch_limit_standard', '3', NOW(), 'Product spec', NULL, 'confirmed'),
('watch_limit_pro', '10', NOW(), 'Product spec', NULL, 'confirmed'),
('route_limit_free', '1', NOW(), 'Product spec', NULL, 'confirmed'),
('route_limit_standard', '3', NOW(), 'Product spec', NULL, 'confirmed'),
('route_limit_pro', '10', NOW(), 'Product spec', NULL, 'confirmed')
ON CONFLICT (key) DO NOTHING;
